name: my_mpt
description: "An application for MPT students that allows you to view the class schedule."
publish_to: 'none'
version: 1.2.0+7

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  flutter_local_notifications: ^18.0.1
  package_info_plus: ^9.0.0
  flutter_rustore_update: ^10.0.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true